// Generated by tools/mkfont.py - see firmware/README.md to regenerate.
// Each theme picks its own pair so the six looks differ in type, not just layout.
#pragma once
#include "ui/gfx.h"

extern const font_t font_sans_8;     // labels, status bar (hand-drawn 5x8) (hand-drawn 5x8)
extern const font_t font_sans_11;    // body
extern const font_t font_sans_16;    // minimal now-playing title
extern const font_t font_slab_22;    // brutalist numerals
extern const font_t font_bold_10;    // brutalist labels
extern const font_t font_mono_8;     // terminal small (hand-drawn 5x8, fixed pitch)
extern const font_t font_mono_12;    // terminal body
extern const font_t font_round_13;   // anime / cassette body
extern const font_t font_round_9;    // anime small
