#!/usr/bin/env python3
"""Bundle the web app into one gzipped file the firmware can serve from flash.

The device has no network, so nothing may be fetched at runtime: CSS, JS, the
glyph tables and the theme code all get inlined into a single index.html, then
gzipped and emitted as a C array. esp_http_server sends it with
Content-Encoding: gzip straight out of the rodata segment - no heap copy, no
filesystem mount.

  ./build.py            # writes dist/index.html(.gz) and ../main/net/www.h
  ./build.py --check    # just report the size against the budget
"""
import argparse, gzip, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
SRC, LIB, DIST = HERE / "src", HERE / "lib", HERE / "dist"
BUDGET = 60 * 1024          # PRODUCT.md: one file, under 60 kB gzipped


def strip_css(css: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    css = re.sub(r"\s*\n\s*", "\n", css)
    css = re.sub(r"\n{2,}", "\n", css)
    return css.strip()


def modules() -> str:
    """Flatten the ES modules into one script, imports resolved by hand.

    Only three files are involved and they form a chain (fonts -> oled -> app),
    so a bundler would be more moving parts than the problem deserves.
    """
    out = []
    for f in (LIB / "fonts.js", LIB / "clock.js", LIB / "oled.js",
              LIB / "data.js", SRC / "app.js"):
        s = f.read_text()
        s = re.sub(r"^\s*import[^;]+;\s*$", "", s, flags=re.M)   # drop imports
        s = re.sub(r"^export (const|function|class) ", r"\1 ", s, flags=re.M)
        s = re.sub(r"^export \{[^}]*\};?\s*$", "", s, flags=re.M)
        # oled.js reads glyphs as F.font_x; everything is one scope now
        s = s.replace("F.font_", "font_")
        out.append(f"/* ---- {f.name} ---- */\n{s}")
    body = "\n".join(out)
    # data.js and app.js both name the demo library; app.js aliased them
    body = body.replace("DEMO_TRACKS", "TRACKS").replace("DEMO_NOW", "NOW") \
               .replace("DEMO_DEVICE", "DEVICE")
    check_collisions(body)
    return body


def check_collisions(body: str) -> None:
    """Flattening four module scopes into one is only safe while the names are
    distinct. `fmt` was declared in both data.js and app.js, which threw at
    parse time and left the page as an empty shell - so the build fails on it
    now instead of the browser."""
    seen, dupes = {}, []
    for i, line in enumerate(body.splitlines(), 1):
        m = re.match(r"(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)", line)
        if not m or line.startswith((" ", "\t")):
            continue
        name = m.group(1)
        if name in seen:
            dupes.append(f"{name} (lines {seen[name]} and {i})")
        seen[name] = i
    if dupes:
        raise SystemExit("build: duplicate top-level names in the bundle: " + ", ".join(dupes))


def build() -> bytes:
    html = (SRC / "index.html").read_text()
    css = strip_css((SRC / "app.css").read_text())
    html = html.replace('<link rel="stylesheet" href="app.css">', f"<style>{css}</style>")
    html = html.replace('<script type="module" src="app.js"></script>',
                        f"<script>\n{modules()}\n</script>")
    assert "app.css" not in html and 'src="app.js"' not in html, "an asset stayed external"
    return html.encode()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    raw = build()
    gz = gzip.compress(raw, 9)
    print(f"index.html  {len(raw):>7,} B raw  ->  {len(gz):>6,} B gzipped "
          f"({len(gz) * 100 // BUDGET}% of the {BUDGET // 1024} kB budget)")
    if len(gz) > BUDGET:
        print("OVER BUDGET", file=sys.stderr)
        return 1
    if a.check:
        return 0

    DIST.mkdir(exist_ok=True)
    (DIST / "index.html").write_bytes(raw)
    (DIST / "index.html.gz").write_bytes(gz)

    hdr = [
        "// Generated by web/build.py - do not edit.",
        "// The whole UI, gzipped, served from rodata with Content-Encoding: gzip.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"#define WWW_INDEX_LEN {len(gz)}",
        "static const uint8_t www_index_gz[] = {",
    ]
    for i in range(0, len(gz), 16):
        hdr.append("    " + ", ".join(f"0x{b:02X}" for b in gz[i:i + 16]) + ",")
    hdr += ["};", ""]
    out = HERE.parent / "main" / "net" / "www.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(hdr))
    print(f"wrote {DIST / 'index.html'}, {DIST / 'index.html.gz'}, {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
